server:
  port: 9001
spring:
  application:
    name: kuke-board-comment-service
  datasource:
    url: jdbc:mariadb://localhost:3306/comment
    username: root
    password: qwe1212!Q
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: none